# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import ns_controller_pb2 as ns__controller__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ns_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NsControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Click = channel.unary_unary(
                '/ns_controller.pb.NsController/Click',
                request_serializer=ns__controller__pb2.ClickRequest.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.Press = channel.unary_unary(
                '/ns_controller.pb.NsController/Press',
                request_serializer=ns__controller__pb2.PressRequest.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.Release = channel.unary_unary(
                '/ns_controller.pb.NsController/Release',
                request_serializer=ns__controller__pb2.ReleaseRequest.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.SetStick = channel.unary_unary(
                '/ns_controller.pb.NsController/SetStick',
                request_serializer=ns__controller__pb2.StickRequest.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.SetState = channel.unary_unary(
                '/ns_controller.pb.NsController/SetState',
                request_serializer=ns__controller__pb2.ControllerState.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/ns_controller.pb.NsController/GetState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.Clear = channel.unary_unary(
                '/ns_controller.pb.NsController/Clear',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ns__controller__pb2.ControllerState.FromString,
                _registered_method=True)
        self.RunMacro = channel.unary_stream(
                '/ns_controller.pb.NsController/RunMacro',
                request_serializer=ns__controller__pb2.Macro.SerializeToString,
                response_deserializer=ns__controller__pb2.MacroEvent.FromString,
                _registered_method=True)


class NsControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Click(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Press(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Release(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Clear(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMacro(self, request, context):
        """Execute a macro on the server with monotonic clock timing.
        Streams progress events back; cancel the stream to abort.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NsControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=ns__controller__pb2.ClickRequest.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'Press': grpc.unary_unary_rpc_method_handler(
                    servicer.Press,
                    request_deserializer=ns__controller__pb2.PressRequest.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'Release': grpc.unary_unary_rpc_method_handler(
                    servicer.Release,
                    request_deserializer=ns__controller__pb2.ReleaseRequest.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'SetStick': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStick,
                    request_deserializer=ns__controller__pb2.StickRequest.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=ns__controller__pb2.ControllerState.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'Clear': grpc.unary_unary_rpc_method_handler(
                    servicer.Clear,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ns__controller__pb2.ControllerState.SerializeToString,
            ),
            'RunMacro': grpc.unary_stream_rpc_method_handler(
                    servicer.RunMacro,
                    request_deserializer=ns__controller__pb2.Macro.FromString,
                    response_serializer=ns__controller__pb2.MacroEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ns_controller.pb.NsController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ns_controller.pb.NsController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NsController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/Click',
            ns__controller__pb2.ClickRequest.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Press(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/Press',
            ns__controller__pb2.PressRequest.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/Release',
            ns__controller__pb2.ReleaseRequest.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/SetStick',
            ns__controller__pb2.StickRequest.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/SetState',
            ns__controller__pb2.ControllerState.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/GetState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Clear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ns_controller.pb.NsController/Clear',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ns__controller__pb2.ControllerState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMacro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ns_controller.pb.NsController/RunMacro',
            ns__controller__pb2.Macro.SerializeToString,
            ns__controller__pb2.MacroEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
