# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ns_controller_pb2 as ns__controller__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ns_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NsControllerStub(object):
    """--- Service ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetState = channel.unary_unary(
                '/controller.v1.NsController/SetState',
                request_serializer=ns__controller__pb2.ControllerState.SerializeToString,
                response_deserializer=ns__controller__pb2.Ack.FromString,
                _registered_method=True)
        self.StreamState = channel.stream_unary(
                '/controller.v1.NsController/StreamState',
                request_serializer=ns__controller__pb2.ControllerState.SerializeToString,
                response_deserializer=ns__controller__pb2.Ack.FromString,
                _registered_method=True)


class NsControllerServicer(object):
    """--- Service ---

    """

    def SetState(self, request, context):
        """Push a single instantaneous state to the server (fire-and-forget semantics
        with an Ack so the client can track drops/retries).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request_iterator, context):
        """Low-latency continuous updates. Client streams states; server sends acks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NsControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=ns__controller__pb2.ControllerState.FromString,
                    response_serializer=ns__controller__pb2.Ack.SerializeToString,
            ),
            'StreamState': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=ns__controller__pb2.ControllerState.FromString,
                    response_serializer=ns__controller__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.v1.NsController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controller.v1.NsController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NsController(object):
    """--- Service ---

    """

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.v1.NsController/SetState',
            ns__controller__pb2.ControllerState.SerializeToString,
            ns__controller__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/controller.v1.NsController/StreamState',
            ns__controller__pb2.ControllerState.SerializeToString,
            ns__controller__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
