# Auto-generated by ns_shiny_hunter configurator — do not edit by hand.
import pathlib

import cv2

from ns_shiny_hunter.frame import ReferenceFrameEnum, ReferenceFrames, FrameProcessors

_HERE = pathlib.Path(__file__).parent


class SwshStaticReferenceFrames(ReferenceFrameEnum):
    ENCOUNTER = ReferenceFrames.template_from_path(
        _HERE / "refs/ENCOUNTER.png",
        threshold=0.85,
        frame_processor=FrameProcessors.all(
            FrameProcessors.crop_rect(110, 592, 354, 38),
            FrameProcessors.CVT_COLOR_BGR2GRAY,
            FrameProcessors.GAUSSIAN_BLUR_DEFAULT,
            FrameProcessors.ADAPTIVE_THRESHOLD_DEFAULT,
        ),
        flags=cv2.IMREAD_GRAYSCALE,
    )

    POKEMON_IN_BATTLE = ReferenceFrames.template_from_path(
        _HERE / "refs/POKEMON_IN_BATTLE.png",
        threshold=0.85,
        frame_processor=FrameProcessors.all(
            FrameProcessors.crop_rect(110, 592, 112, 40),
            FrameProcessors.CVT_COLOR_BGR2GRAY,
            FrameProcessors.GAUSSIAN_BLUR_DEFAULT,
            FrameProcessors.ADAPTIVE_THRESHOLD_DEFAULT,
        ),
        flags=cv2.IMREAD_GRAYSCALE,
    )
